image: node:latest

pages:
  script:
    - npm install
    - npm run build
    - rm -rf public/*
    - cp -rT build public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
